import { ObjectType, InputType, Field, ID, Int, registerEnumType } from '@nestjs/graphql';
import { SideEffectSeverity } from '@prisma/client';

registerEnumType(SideEffectSeverity, { name: 'SideEffectSeverity' });
export { SideEffectSeverity };

@InputType()
export class ReportSideEffectsInput {
  @Field(() => [String], { description: 'Keys of the effects, e.g. "nausea"' })
  effects: string[];

  @Field(() => SideEffectSeverity)
  severity: SideEffectSeverity;

  @Field({ nullable: true })
  note?: string;
}

@ObjectType('SideEffectReport')
export class SideEffectReportModel {
  @Field(() => ID)
  id: string;

  @Field(() => [String])
  effects: string[];

  @Field(() => SideEffectSeverity)
  severity: SideEffectSeverity;

  @Field({ nullable: true })
  note?: string;

  @Field({ nullable: true, description: 'What the patient was on when they reported it' })
  medication?: string;

  @Field()
  createdAt: Date;

  @Field({ nullable: true })
  acknowledgedAt?: Date;

  @Field({ nullable: true, description: 'What to tell the patient right after reporting; set only when there is something to say' })
  advice?: string;
}

@ObjectType('SideEffectAlert', { description: 'A side effect a patient reported that no doctor has acknowledged yet' })
export class SideEffectAlertModel extends SideEffectReportModel {
  @Field(() => ID)
  patientId: string;

  @Field()
  patientName: string;
}

@InputType()
export class LogSideEffectScoresInput {
  @Field(() => Int, { description: '1 = none, 10 = the worst' })
  nausea: number;

  @Field(() => Int)
  vomiting: number;

  @Field(() => Int)
  abdominalPain: number;

  @Field(() => Int)
  diarrhoea: number;

  @Field(() => Int)
  constipation: number;

  @Field(() => Int)
  fatigue: number;

  @Field({ nullable: true })
  note?: string;

  @Field({ nullable: true, description: 'Generated by the client per form submission so a retry or double tap records it once' })
  clientRequestId?: string;
}

@ObjectType('SideEffectScoreEntry')
export class SideEffectScoreEntryModel {
  @Field(() => ID)
  id: string;

  @Field()
  recordedAt: Date;

  @Field(() => Int)
  nausea: number;

  @Field(() => Int)
  vomiting: number;

  @Field(() => Int)
  abdominalPain: number;

  @Field(() => Int)
  diarrhoea: number;

  @Field(() => Int)
  constipation: number;

  @Field(() => Int)
  fatigue: number;

  @Field({ nullable: true })
  note?: string;

  @Field({ nullable: true, description: 'What to tell the patient right after saving; set only when a score is high' })
  advice?: string;
}

@ObjectType('SideEffectScoreRow')
export class SideEffectScoreRowModel {
  @Field()
  key: string;

  @Field()
  label: string;

  @Field(() => Int)
  latest: number;

  @Field(() => Int, { nullable: true, description: 'The entry before the latest' })
  previous?: number | null;

  @Field(() => Int, { description: 'Highest in the last 28 days' })
  peak: number;

  @Field({ description: 'At or above the level that needs the doctor’s attention' })
  flagged: boolean;

  @Field({ description: 'Gone up sharply since the entry before' })
  rising: boolean;
}

@ObjectType('SideEffectSummary', { description: 'Everything a doctor should see about a patient’s side effects before approving their next supply or dose' })
export class SideEffectSummaryModel {
  @Field({ nullable: true })
  lastLoggedAt?: Date | null;

  @Field(() => Int, { nullable: true })
  daysSinceLastLog?: number | null;

  @Field({ description: 'No weekly entry lately (or ever), so the scores may be out of date. Not the same as no side effects.' })
  stale: boolean;

  @Field(() => [SideEffectScoreRowModel])
  scores: SideEffectScoreRowModel[];

  @Field(() => [SideEffectScoreEntryModel], { description: 'The most recent weekly entries, newest first' })
  entries: SideEffectScoreEntryModel[];

  @Field(() => [SideEffectReportModel], { description: 'Side effects the patient reported themselves in the last 28 days' })
  reports: SideEffectReportModel[];

  @Field(() => Int, { description: 'Recent doses after which the patient said they felt unwell' })
  roughDoses: number;

  @Field()
  needsAttention: boolean;

  @Field(() => [String], { description: 'Why it needs attention, in plain words' })
  reasons: string[];
}
