import { Field, Float, InputType } from '@nestjs/graphql';

@InputType()
export class AddBodyMeasurementInput {
  @Field(() => Float, { nullable: true, description: 'Waist in cm, 30–250' })
  waistCm?: number;

  @Field(() => Float, { nullable: true, description: 'Hips in cm, 40–250' })
  hipsCm?: number;

  @Field(() => Float, { nullable: true, description: 'Upper arm in cm, 10–100' })
  armCm?: number;

  @Field({ nullable: true, description: 'When measured. Defaults to now; can be in the past, never the future.' })
  measuredAt?: Date;

  @Field({ nullable: true, description: 'Generated by the client per form submission so a retry or double tap records it once' })
  clientRequestId?: string;
}
