import { InputType, Field, ID, Float } from '@nestjs/graphql';

@InputType()
export class CorrectWeightGoalInput {
  @Field(() => ID)
  patientId: string;

  @Field(() => Float, { nullable: true })
  startingWeightKg?: number;

  @Field(() => Float, { nullable: true })
  targetWeightKg?: number;

  @Field({ nullable: true, description: 'Kept in the audit log' })
  reason?: string;
}

@InputType()
export class CorrectCheckInWeightInput {
  @Field(() => ID)
  checkInId: string;

  @Field(() => Float)
  weightKg: number;

  @Field({ nullable: true, description: 'Kept in the audit log' })
  reason?: string;
}

@InputType()
export class AddWeightInput {
  @Field(() => Float)
  weightKg: number;

  @Field({ nullable: true, description: 'When it was weighed. Defaults to now; can be in the past, never the future.' })
  measuredAt?: Date;

  @Field({ nullable: true })
  note?: string;

  @Field({ nullable: true, description: 'Generated by the client per form submission so a retry or double tap records it once' })
  clientRequestId?: string;

  @Field(() => ID, { nullable: true, description: 'A progress photo already uploaded (kind PROGRESS_PHOTO) to keep with this weighing' })
  photoFileId?: string;
}

@InputType()
export class EditMyWeightInput {
  @Field(() => ID)
  entryId: string;

  @Field(() => Float, { nullable: true, description: 'Leave out to keep the weight' })
  weightKg?: number;

  @Field({ nullable: true, description: 'Leave out to keep the date. Can be in the past, never the future.' })
  measuredAt?: Date;

  @Field({ nullable: true, description: 'Leave out to keep the note; an empty string removes it' })
  note?: string;

  @Field(() => ID, { nullable: true, description: 'A progress photo already uploaded, to replace the one kept with this weighing' })
  photoFileId?: string;

  @Field({ nullable: true, description: 'Take the photo off this weighing. The picture itself is then erased.' })
  removePhoto?: boolean;
}

@InputType()
export class CorrectWeightEntryInput {
  @Field(() => ID)
  entryId: string;

  @Field(() => Float)
  weightKg: number;

  @Field({ description: 'Kept in the audit log' })
  reason: string;
}
