import { InputType, Field, ID, Float } from '@nestjs/graphql';

@InputType()
export class CorrectWeightGoalInput {
  @Field(() => ID)
  patientId: string;

  @Field(() => Float, { nullable: true })
  startingWeightKg?: number;

  @Field(() => Float, { nullable: true })
  targetWeightKg?: number;

  @Field({ nullable: true, description: 'Kept in the audit log' })
  reason?: string;
}

@InputType()
export class CorrectCheckInWeightInput {
  @Field(() => ID)
  checkInId: string;

  @Field(() => Float)
  weightKg: number;

  @Field({ nullable: true, description: 'Kept in the audit log' })
  reason?: string;
}

@InputType()
export class AddWeightInput {
  @Field(() => Float)
  weightKg: number;

  @Field({ nullable: true, description: 'When it was weighed. Defaults to now; can be in the past, never the future.' })
  measuredAt?: Date;

  @Field({ nullable: true })
  note?: string;

  @Field({ nullable: true, description: 'Generated by the client per form submission so a retry or double tap records it once' })
  clientRequestId?: string;
}

@InputType()
export class CorrectWeightEntryInput {
  @Field(() => ID)
  entryId: string;

  @Field(() => Float)
  weightKg: number;

  @Field({ description: 'Kept in the audit log' })
  reason: string;
}
